Update to version 1.0.9
* - Fixed "Uncaught TypeError: $(...).flickity is not a function" error.
* - Moved .menu-toggle further down when .admin-bar is active.
* - Added box-shadow when focus is on input for better accessibility.